runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
    DB_USER: "postgres"
    DB_NAME: "postgres"
    INSTANCE_CONNECTION_NAME: "stoked-depth-428423-j7:us-central1:golf-better"

handlers:
- url: /api/v1/.*
  script: auto

- url: /protected/.*
  script: auto
  login: required
  secure: always

- url: /.*
  script: auto
  login: required
  secure: always

