name: Refresh Leaderboards Function CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r gcp/cloud-functions/refresh-leaderboards/requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pytest-mock
        pytest gcp/cloud-functions/refresh-leaderboards --doctest-modules --junitxml=junit/gcp/cloud-functions/refresh-leaderboards/test-results.xml --cov=com --cov-report=xml --cov-report=html
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check --output-format=github gcp/cloud-functions/refresh-leaderboards
      continue-on-error: true